name: Run ESLint
on:
    push:
        branches: "*"
    pull_request:
        branches: [main]
jobs:
    prettier:
        name: Run ESLint
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install modules
              run: npm install
            - name: Check eslint
              run: npx eslint src --ext .js,.vue
